# -*- coding: utf-8 -*-
"""Подставкин Д.С..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cR0YADNLF84QboAG_-tccaAT2xYcxZUr
"""

from google.colab import files
uploaded = files.upload()

df

import pandas as pd
#import numpy as np
df = pd.read_csv("country_vaccinations.csv")
print(df.shape)                #размер дата фрейма
print(df.isna().sum())            #количество пустых значений
print(df.dtypes)                  #типы данных
for i in range(len(df.dtypes)):   #Поиск категориальных признаков
  if df.dtypes[i] == 'object':
    print(df.columns[i], df.dtypes[i])

colum = df.columns              #удаление столбцов если Nan > 1/2
for i in range(0, len(colum)):
  if df[colum[i]].isna().sum() > df.shape[0] / 2:
    df = df.drop([colum[i]], axis = 1)
print(df)

print(df.fillna(df.mean()))        #Заменяем пустые значения средним
df.dropna()                       #удаление строк если имеет Nan

